application: emccdb
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /stats.*
  script: google.appengine.ext.appstats.ui.app
- url: /.*
  script: main.application
  secure: always

libraries:
- name: webapp2
  version: latest

builtins:
- appstats: on
- remote_api: on
